### ISSUE TITLE
 PayHere Error = Unable to initilize the payment at the moment

### ISSUE THREAD

**Issue by Ilthizam** [Thisura98/payhere-angular-example#1]
> 
>  zone.js:2892 Access to XMLHttpRequest at 'https://sandbox.payhere.lk/pay/checkout' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> 
> PayHere Error = Unable to initilize the payment at the moment
>

**Comment by Thisura98** [comment]
Hello, @Ilthizam 
Just checked by making a payment using the code and it was successful. I did not receive this error. It could be a temporary downtime on PayHere's side. 

Could you kindly check again and let me know if the issue still exists?

**Comment by Thisura98** [comment]
Closing this since I haven't heard from you in a while.
